[2025-02-24T10:44:58.668+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_processing_dag.load_resources manual__2025-02-24T04:44:12.365870+00:00 [queued]>
[2025-02-24T10:44:58.670+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_processing_dag.load_resources manual__2025-02-24T04:44:12.365870+00:00 [queued]>
[2025-02-24T10:44:58.670+0530] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2025-02-24T10:44:58.674+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_resources> on 2025-02-24 04:44:12.365870+00:00
[2025-02-24T10:44:58.678+0530] {standard_task_runner.py:57} INFO - Started process 6571 to run task
[2025-02-24T10:44:58.681+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_processing_dag', 'load_resources', 'manual__2025-02-24T04:44:12.365870+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/var/folders/kz/_l5jq2xx6db29k_3xyv2j8n40000gp/T/tmp3jk2tixs']
[2025-02-24T10:44:58.681+0530] {standard_task_runner.py:85} INFO - Job 71: Subtask load_resources
[2025-02-24T10:44:58.700+0530] {task_command.py:416} INFO - Running <TaskInstance: fraud_detection_processing_dag.load_resources manual__2025-02-24T04:44:12.365870+00:00 [running]> on host ninja-its-macbook-air-90.local
[2025-02-24T10:44:58.771+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_processing_dag' AIRFLOW_CTX_TASK_ID='load_resources' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T04:44:12.365870+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-24T04:44:12.365870+00:00'
[2025-02-24T10:44:58.771+0530] {data_pipeline_dag.py:34} INFO - Loading model and scaler...
[2025-02-24T10:44:58.860+0530] {data_pipeline_dag.py:41} INFO - Model and scaler loaded successfully.
[2025-02-24T10:44:58.860+0530] {python.py:194} INFO - Done. Returned value was: {'model': RandomForestClassifier(class_weight='balanced', max_depth=15,
                       min_samples_leaf=4, min_samples_split=10,
                       n_estimators=40, n_jobs=-1, random_state=42), 'scaler': StandardScaler()}
[2025-02-24T10:44:58.862+0530] {xcom.py:661} ERROR - Object of type RandomForestClassifier is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2025-02-24T10:44:58.862+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'sklearn.ensemble._forest.RandomForestClassifier'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RandomForestClassifier is not JSON serializable
[2025-02-24T10:44:58.870+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=fraud_detection_processing_dag, task_id=load_resources, execution_date=20250224T044412, start_date=20250224T051458, end_date=20250224T051458
[2025-02-24T10:44:58.874+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 71 for task load_resources (Object of type RandomForestClassifier is not JSON serializable; 6571)
[2025-02-24T10:44:58.907+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-24T10:44:58.916+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
